version: '3.8'

services:
  postgres_server:
    build:
      context: .
      dockerfile: ../dockerfiles/dockerfile-postgres
    container_name: postgres_server_container
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      example_network:
        ipv4_address: 10.5.0.7
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  example_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
